import './src/nav-bar'
import './src/my-email-input'
import './src/my-password-input'
import './src/my-submit-button'
import './src/login-form-normal-inputs'
import './src/login-form-custom-inputs'
import './src/my-footer'
